### ISSUE TITLE
preliminary back extension slated to be deprecated now back extension is available

### ISSUE THREAD

**Issue by bvreede** [eWaterCycle/era5cli#115]
Dear ERA5 reanalysis users,
You may recall that in 2020, a pre-release quality control of the ERA5 back extension had revealed some problems affecting the performance in the tropics. We are pleased to inform our users that the Copernicus Climate Change Service (C3S) at ECMWF has now released an updated version of the ERA5 back extension data covering the period 1959-1978 in the Climate Data Store (CDS). For details, please refer to our article explaining the [Changes in the ERA5 back extension compared to its preliminary version](https://confluence.ecmwf.int/x/xSmaE) 
The updated version of the back extension has been added to the ERA5 catalogue entries:
[ERA5 hourly data on single levels from 1959 to present](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels?tab=overview) 
[ERA5 hourly data on pressure levels from 1959 to present](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-pressure-levels?tab=overview) 
[ERA5 monthly averaged data on pressure levels from 1959 to present](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-pressure-levels-monthly-means?tab=overview) 
[ERA5 monthly averaged data on single levels from 1959 to present](https://cds.climate.copernicus.eu/cdsapp#!/dataset/reanalysis-era5-single-levels-monthly-means?tab=overview)
**For the time being, the Preliminary back extension data (1950-1978) continue to be made available to download from the CDS but will eventually be deprecated. The ERA5 back extension covering the period 1950-1958 will ultimately be updated and added to the ERA5 catalogue entries.**
To download the ERA5 data, please follow our guidelines on [How to download ERA5](https://confluence.ecmwf.int/display/CKB/How+to+download+ERA5)
Should you have any enquiries, please do not reply to this message but raise a ticket using our [Support Portal](https://confluence.ecmwf.int/category/cd). Thank you.
Regards,
ECMWF Support

**Comment by BSchilperoort** [comment]
Related to #124. I'll close this one, as we will wait until the 1950-1959 data is available on the (non-preliminary) back extension.
