### ISSUE TITLE
Deprecate preliminary back extension support

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/era5cli#124]
In #123 support is added for the "normal" back extension. That means that the preliminary back extension will be less relevant. Since the preliminary back extension adds substantial complexity to this tool, we might want to think about deprecating it. Users relying on the back extension for the reproducibility of previous results could still use an older version of era5cli.

**Comment by malininae** [comment]
@Peter9192 Although I agree it's less relevant now, but there are still nine years that one wants to download through the back extension (1950-1958). I would suggest keeping it for a bit.

**Comment by BSchilperoort** [comment]
That could work. I'll make the usage of `--prelimbe` raise a deprecation warning, and remove it in a later release.
