### ISSUE TITLE
Update python versions in CI

### ISSUE THREAD

**Issue by BSchilperoort** [eWaterCycle/era5cli#127]
Currently the CI covers Python 3.6, 3.7, 3.8 and 3.9. However, Python 3.6 reached its end-of-life almost a year ago. Additionally, Python 3.10 has already been released for a year.

Is there a reason to keep the CI for Python 3.6? Or should 3.6 be dropped and 3.10 added?

Related to #119

**Comment by bvreede** [comment]
Python 3.6 is no longer available, or so I interpret [this failing action](https://github.com/eWaterCycle/era5cli/actions/runs/3680649031/jobs/6226477169#step:3:8).

**Comment by BSchilperoort** [comment]
> Python 3.6 is no longer available, or so I interpret [this failing action](https://github.com/eWaterCycle/era5cli/actions/runs/3680649031/jobs/6226477169#step:3:8).

Yes, Github Actions is moving towards Ubuntu 22 (`ubuntu-latest` in the configuration), which does not support Python 3.6. It would still be possible to have the CI work, by setting `runs-on: ubuntu-20.04`, but I tihnk we don't want to support 3.6 anyway.
