### ISSUE TITLE
CDS beta error upon attempt_cds_login

### ISSUE THREAD

**Issue by jannesvaningen** [eWaterCycle/era5cli#168]
I tried configuring era5cli with the new beta version 2.0.0b1. I run into an error when reconfiguring the era5cli config using:
`era5cli config --key "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx"` (with my new key on the CDS-beta).
The warning I get is:
`*** requests.exceptions.MissingSchema: Invalid URL 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx': No scheme supplied. Perhaps you meant https://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx/profiles/v1/account/verification/pat?`
Which looks like it tries to use the key as the url? I checked and the problem lies in:
https://github.com/eWaterCycle/era5cli/blob/52a6a2d13c70c19049552edbe3452f1665cd19f2/era5cli/key_management.py#L37
It looks like the arguments for key and url should be flipped, because the returned statement I get from that line is:
`ApiClient(url='xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx', key='https://cds-beta.climate.copernicus.eu/api', verify=True, timeout=60, progress=True, cleanup=False, sleep_max=120, retry_after=120, maximum_tries=500, session=<requests.sessions.Session object at 0xee39b372fa60>)`

Proposed solution:
change https://github.com/eWaterCycle/era5cli/blob/52a6a2d13c70c19049552edbe3452f1665cd19f2/era5cli/key_management.py#L37
to `client = cads_api_client.ApiClient(url,key) `

**Comment by BSchilperoort** [comment]
Strange, when I do 
```py
import cads_api_client
help(cads_api_client.ApiClient)
```
I get:
```
Help on class ApiClient in module cads_api_client.api_client:

class ApiClient(builtins.object)
 |  ApiClient(key: 'str | None' = None, url: 'str | None' = None, sleep_max: 'int' = 120, cleanup: 'bool' = False, session: 'requests.Session' = NOTHING) -> None
 |  
 |  Methods defined here:
...
```
which is the other way around :roll_eyes: 

Turns out https://github.com/ecmwf-projects/cads-api-client/pull/69 switched the arguments around (accidentally?) which was released in a patch version (1.3.1).

I can fix this by using them as kwargs instead, so the order shouldn't matter.

**Comment by jannesvaningen** [comment]
Ah that's annoying. It works for me locally if I turn them around.
Kwargs are a good solution I guess.

**Comment by BSchilperoort** [comment]
> Ah that's annoying. It works for me locally if I turn them around.

Yeah it'll depend on the version of the cads api you have installed

**Comment by BSchilperoort** [comment]
I decided to just hard pin the cads api for now
