### ISSUE TITLE
Store API key using the cli. Avoid overlap with Atmosphere Data Store key

### ISSUE THREAD

**Issue by jeromaerts** [eWaterCycle/era5cli#31]
Ask the user in the command line to fill in the URL and API Key, so that the .cdsapirc will be automatically generated.

**Comment by BSchilperoort** [comment]
In addition to this, storing the API key in a different file, only for era5cli, could be useful as well. The [ADS](https://ads.atmosphere.copernicus.eu/#!/home) uses the cds API, including the `.cdsapirc` file but with a different URL and different API keys.

**Comment by Peter9192** [comment]
or `~/.config/era5cli` for consistency with `~/.config/ewatercycle.yaml`?
