### ISSUE TITLE
Add support for regional subselection

### ISSUE THREAD

**Issue by JaroCamphuijsen** [eWaterCycle/era5cli#44]
From the [CDS documentation](https://confluence.ecmwf.int/display/CKB/How+to+download+ERA5):

> Currently the interactive CDS forms don't allow users to perform a regional sub-selection or an interpolation of the selected data. However, both actions can be performed using the following CDS API keywords:
For a geographical area subset, use key area.
For a different grid resolution, use key grid.
Please note that the ERA5 native grid in CDS is 0.25°x0.25° (atmosphere), 0.5°x0.5° (ocean waves), Mean, spread and members: 0.5°x0.5° (atmosphere), 1°x1° (ocean waves).

We want to integrate this option in era5cli.

**Comment by Peter9192** [comment]
For an example, see [this web page](https://confluence.ecmwf.int/display/CKB/How+to+download+ERA5), under section 3B: 

> Show basic CDS API script including geographical subset
