### ISSUE TITLE
Handling requests for exceeding number of items

### ISSUE THREAD

**Issue by JaroCamphuijsen** [eWaterCycle/era5cli#46]
Implement a check on number of items to be downloaded, before sending the request and potentially split the request in multiple smaller requests, or give user a message. 

---------------------------------------
*Example:*
Upon sending a reasonable request:
`era5cli hourly --variable u_component_of_wind --startyear 2008 --ensemble --statistics`

cds raises the following exception:
`Exception: the request you have submitted is not valid. Request too large. Requesting 975024 items, limit is 120000.
`

**Comment by SarahAldt** [comment]
@JaroCamphuijsen it might be useful:
https://confluence.ecmwf.int/display/WEBAPI/ERA5+daily+retrieval+efficiency

**Comment by BSchilperoort** [comment]
@SarahAlidoost it seems like we should also split up requests by month for ensemble downloads, just like we are planning to do for era5land data. That would allow us to resolve this issue.

Related to #133

**Comment by BSchilperoort** [comment]
Fixed in #139
