### ISSUE TITLE
Documentation reflects master, not latest release

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/era5cli#72]
After merging #70 I noticed that the documentation included in this PR is already published on readthedocs. I had expected that this would only happen after a new release. I think it would be good to change the 'latest' tag to the latest official release here https://readthedocs.org/projects/era5cli/.

**Comment by bvreede** [comment]
I switched the tag to 'stable'; this will find the latest release on GitHub and use it for the primary readthedocs page.
