### ISSUE TITLE
Add link to documentation in GH about section

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/era5cli#73]
To make it easier to find the documentation from GH, we could add a link to the about section of the repo: 
![image](https://user-images.githubusercontent.com/17080502/109950399-bf5b1980-7cdc-11eb-8882-a496c7081344.png)

**Comment by nielsdrost** [comment]
@Peter9192 You should be able to set this now, let me know if this is not the case :-)

**Comment by Peter9192** [comment]
Yes, thanks! 
Done :-)
