### ISSUE TITLE
Better documentation about coordinate variables

### ISSUE THREAD

**Issue by bvreede** [eWaterCycle/era5cli#74]
Currently, some necessary clarity is missing in the documentation in how coordinates are treated by the tool. Because coordinates are given in four separate but not individually labeled numbers, it is important that it is clear to the user what sequence they should be given in.

- when calling `era5cli hourly --help`, area variable help is given as `[--area AREA AREA AREA AREA]`, instead of specifying explicitly what order the coordinates are supposed to be given in. It should be possible to change this to, e.g. `[--area LAT_MAX LON_MIN LAT_MIN LON_MAX]`. See [argparse documentation](https://docs.python.org/3/library/argparse.html#metavar) for how to implement this.
- Use of x and y (as `xmin` e.g.), currently used in the `--help`, may be confusing as well, and should be replaced by clearer terms like longitude and latitude.

**Comment by Peter9192** [comment]
I propose:

xmin --> lonmin
xmax --> lonmax
ymin --> latmin
ymax --> latmax
