### ISSUE TITLE
search function for variables

### ISSUE THREAD

**Issue by bvreede** [eWaterCycle/era5cli#75]
Calling all variables with e.g. `era5cli info 2Dvars` yields a long list.
You can use a search function in bash to narrow down the selection, like `era5cli info 2Dvars | grep "temperature"`, but I wonder how many users know this? Is this expected knowledge?

If not, should we recommend this in the documentation?

Or implement a variable search in era5cli itself?

**Comment by nielsdrost** [comment]
I would add a note to the documentation, good idea! Implementing a search function implies adding yet more command line options, which I think we should avoid
