### ISSUE TITLE
orcids missing for authors

### ISSUE THREAD

**Issue by nielsdrost** [eWaterCycle/era5cli#78]
The .zenodo.json file does not contain the ORCIDs of the authors. Adding this will help adding era5cli to the publication records of the authors.

Also, there are a few authors missing.

**Comment by Peter9192** [comment]
I think the zenodo file is created from the citation.cff, no? So we should probably (also) add them there.

**Comment by bvreede** [comment]
Do you know how the zenodo file gets created, @Peter9192? I've added orcids & authors to the cff file, but not sure how they get imported to zenodo now.

**Comment by Peter9192** [comment]
There is a tool cff-convert that can create the zenodo file for you: https://github.com/citation-file-format/cff-converter-python

**Comment by Peter9192** [comment]
Also see the instructions here: https://guide.esciencecenter.nl/#/citable_software/making_software_citable
