### ISSUE TITLE
Add support for ERA5-land back extension

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/era5cli#99]
Dear ERA5-Land reanalysis users,

We are pleased to inform you that the Copernicus Climate Change Service (C3S) at ECMWF has released the ERA5-Land hourly data for the period 1950-1980 (referred to as the ERA5-Land back extension (BE)).

Access to ERA5 BE is available from the Climate Data Store (CDS) either interactively using the ERA5-Land hourly download data form or programmatically using the CDS API service.

ERA5-Land documentation has been updated.

The Daily statistics calculated from ERA5 data application is also to be shortly updated to include ERA5-Land BE. This application allows users to compute and download selected daily statistics in local time (via the Time zone widget) of variables from a number of hourly ERA5 reanalysis datasets.

If you have any questions or feedback about our ERA5 products or wish to keep updated with the latest announcements including future releases of additional ERA5 products (e.g. ERA5-Land monthly averaged data for the period 1950-1980), we invite you to visit and 'watch' our User Forum C3S Announcements. Alternatively, you may contact us.

Yours sincerely,

ECMWF Support

**Comment by BSchilperoort** [comment]
With the back extension being deprecated (base ERA5-land now includes the back extension), this is not relevant anymore.
